config/routes.rb
Rails.application.routes.draw do
  root "chatroom#index"
  # messsage
  post "/message", to: "messages#create"
  # session
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/login", to: "sessions#destroy"
  # users
  get "/sign-up", to: "users#new"
  match "/sign-up", via: :post, to: "users#create"
  resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  validates :body, presence: true
  belongs_to :user

  after_create_commit -> { broadcast_append_to "chatroom_channel", partial: "chatroom/message", locals: { quote: self }, target: "chat" }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :messages, :dependent => :destroy
  validates :username, presence: true, length: { minimum: 3, maximum: 25 }, uniqueness: { case_sensitive: false }
  validates :terms, acceptance: true
  validates :password, confirmation: true, presence: true, length: { minimum: 6, maximum: 25 }
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:warning] = "You must be logged in to perform that action."
      redirect_to login_path
    end
  end

end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController

  def index
    @messages = Message.last(30)
    @users = User.last(10)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def new
    @message = Message.new
  end

  def create
    @message = current_user.messages.build(message_params)
    if @message.save
      respond_to do |format|
        format.turbo_stream
      end
    else
      flash[:warning] = "The message was not sent."
    end
  end

  private
  def message_params
    params.require(:message).permit(:body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_not_logged_in, only: [:new, :create]

  def new
  end

  def create
    credentials = login_params
    user = User.find_by(username: credentials[:username])
    if user && user.authenticate(credentials[:password])
      cookies[:username] = user.username
      session[:user_id] = user.id
      flash[:success] = "Welcome back, #{user.username}!"
      redirect_to root_path
    else
      flash.now[:error] = "Log in failed. Wrong credentials."
      render :new
    end
  end

  def destroy
    flash[:success] = "Logged out succefully. Take care #{current_user.username}!"
    cookies[:username] = 'guest'
    session[:user_id] = nil
    redirect_to root_path, status: :see_other
  end

  private
  def login_params
    params.require(:session).permit(:username, :password)
  end

  def require_not_logged_in
    if logged_in?
      redirect_to root_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :show, :update]
  before_action :require_user, only: [:edit, :show, :update]

  def new
    @user = User.new
  end

  def show
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Account created successfully. You may login now!"
      redirect_to login_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    params = change_password_params
    if @user.authenticate(params[:old_password]) && @user.update({
      :password => params[:password],
      :password_confirmation => params[:password_confirmation]
    })
      flash[:success] = "Password changed successfully! Log in again."
      session[:user_id] = nil
      redirect_to root_path
    else
      flash[:error] = "Password change failed! Check your password."
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :terms)
  end

  def change_password_params
    params.require(:user).permit(:password, :password_confirmation, :old_password)
  end

  def set_user
    @user = User.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_avatar_for_username(username)
    seed = username.bytes.join
    src = "https://avatars.dicebear.com/api/big-smile/#{seed[0, 10]}.svg"
    image_tag(src, alt: username, class: "ui avatar image")
  end

end

app/views/chatroom/_chat.html.erb
<div class="ui raised padded blue secondary small segment container">

  <h2 class="ui header center aligned">
    <span class="content">Chatroom</span>
    <div class="sub header">Stay connected with your loved ones</div>
  </h2>

  <%= turbo_stream_from "chatroom_channel" %>

  <div class="ui segment container minimal comments" style="overflow-y: scroll; height: 32vh; max-height: 64vh" data-controller="chat" >
    <%= turbo_frame_tag "chat" do %>
      <%= render "chat_placeholder" %>
      <% if logged_in? %>
        <% @messages.each do |message| %>
          <%= render "message", message: message %>
        <% end %>
      <% else %>
        <%= render "chat_placeholder" %>
      <% end %>

    <% end %>
  </div>

  <%= form_with scope: :message, role: "form", class: "ui form items",
      data: { controller: "new-message", action: "turbo:submit-end->new-message#reset" },
      url: message_path do |form|
  %>
    <div class="field ui grid container">
      <%= form.text_field :body, placeholder: "Enter your message...", class: "thirteen wide column" %>
      <%= form.submit "Send", class: "three wide column blue button fluid right floated ui" %>
    </div>
  <% end %>

</div>

app/views/chatroom/_chat_placeholder.html.erb
<div class="ui fluid placeholder" id="messages-placeholder">
  <% for i in 0..4 do %>
    <div class="image header">
      <div class="line"></div>
      <div class="line"></div>
    </div>
  <% end %>
</div>

app/views/chatroom/_comment.html.erb
  <div class="comment">
    <a class="avatar">
      <%= random_avatar_for_user("Natalka") %>
    </a>
    <div class="content">
      <a class="author">Natalka</a>
      <div class="metadata">
        <span class="date">Today at 5:43PM</span>
      </div>
      <div class="text">
        How artistic!
      </div>
      <div class="actions">
        <a class="reply">Reply</a>
      </div>
    </div>
  </div>

app/views/chatroom/_message.html.erb
<turbo-stream action="append" target="chat">
  <template>
    <%= turbo_frame_tag message do %>
      <div class="comment" id="message" data-chat-target="message">
        <a class="avatar">
          <%= get_avatar_for_username("#{message.user.username}") %>
        </a>
        <div class="content">
          <%= link_to message.user.username, message.user, class: "author" %>
          <div class="metadata">
            <span class="date">
              <%= distance_of_time_in_words_to_now message.created_at %> ago
            </span>
          </div>
          <div class="text">
            <%= message.body %>
          </div>
        </div>
      </div>
    <% end %>
  </template>
</turbo-stream>

app/views/chatroom/_user_list.html.erb
<div class="ui raised padded blue secondary small segment container">

  <h2 class="ui header center aligned">
    <span class="content">New users</span>
    <div class="sub header">Meet new friends</div>
  </h2>

  <section class="ui unstackable items animated list">
    <% if logged_in? %>
      <% if @users %>
        <% @users.each do |user| %>
          <div class="item">
            <div class="ui tiny image">
              <%= get_avatar_for_username("#{user.username}") %>
            </div>
            <div class="middle aligned content">
              <%= link_to user.username, user, class: "ui header" %>
              <div class="description">
                  Joined <%= time_ago_in_words user.created_at %> ago
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <div class="ui fluid placeholder">
        <div class="image header">
          <div class="line"></div>
          <div class="line"></div>
        </div>
        <div class="image header">
          <div class="line"></div>
          <div class="line"></div>
        </div>
      </div>
    <% end %>
  </section>
</div>

app/views/chatroom/index.html.erb
<main>

  <section class="<%= class_names('ui', 'centered', 'blurring', 'stackable', 'padded', 'grid', 'disable-select': !logged_in?)%>"
          style="<%="pointer-events:none; user-select: none;" if !logged_in?%>"
  >

      <div class="ten wide column">
        <%= render "chat" %>
      </div>

      <div class="six wide column">
        <%= render "user_list" %>
      </div>

      <div class="<%= class_names('dimmable', 'hidden': logged_in?, 'ui inverted dimmer': !logged_in?)%>", style="pointer-events: none;">
        <div class="ui massive segment" style="pointer-events: auto;">
          <i class="wechat icon"></i>
            <%= link_to "Log in ", login_path %>
            to join chat!
          </h2>
        </div>
      </div>

  </section>

</main>

app/views/chatroom/messages/_my_message.html.erb
<div class="ui segment small basic clearing"> <!-- clearing for my messages -->
  <div class="comment ui segment right floated basic"> <!-- right floated for my messages -->
    <a class="avatar">
      <%= get_avatar_for_username("#{message.user.username}") %>
    </a>
    <div class="content">
      <a class="author">
        <%= link_to message.user.username, message.user, class: "author" %>
      </a>
      <div class="metadata">
        <span class="date">
          <%= distance_of_time_in_words_to_now message.created_at %> ago
        </span>
      </div>
      <div class="text">
        <%= message.body %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "script.js", :defer => "defer" %>
  </head>
  <body>
    <%= render "shared/nav" %>

    <div class="ui container">
      <%= yield %>
    </div>

    <%= render "shared/flash" %>
  </body>
</html>

app/views/shared/_flash.html.erb
<div style="position: fixed; bottom: 20px; right: 20px;">
  <% flash.each do |name, msg| %>
    <div class="<%= "ui floating message #{name} transition" %>">
      <i class="close icon"></i>
      <div class="header">
        <%= name.capitalize %>
      </div>
      <p>
        <%= msg %>
      </p>
    </div>
  <% end %>
</div>

app/views/shared/_nav.html.erb
<nav class="ui borderless inverted tiny menu" style="border-radius: 0;">
  <div class="ui container">
    <%= link_to "Chatroom", root_path, class: "item ui sized large header " %>

    <div class="right menu">

      <div class="item">
        <div class="ui primary">
          <% if logged_in? %>
            <%= link_to raw("<i class=\"alternative sign in icon\"></i>Log out"), login_path, data: { "turbo-method": :delete }, class: "ui primary fluid button" %>
          <% else %>
            <%= link_to raw("<i class=\"alternative sign in icon\"></i>Log in"), login_path, class: "ui primary fluid button" %>
          <% end %>
        </div>
      </div>

      <% if logged_in? %>
          <div class="item dropdown ui primary button">
            Account
            <i class="dropdown icon"></i>
            <div class="menu">
              <%= link_to "Change password", edit_user_path(current_user), class: "ui link item" %>
            </div>
          </div>

      <% end %>

    </div>

  </div>
</nav>

app/views/shared/_validation_errors.html.erb
<section class="ui segment small basic">
  <% if model.errors.any? %>
    <div class="ui error floating tiny message">
      <i class="close icon"></i>
      <div class="header">
        There were some errors with account creation
      </div>
      <ul class="list">
          <% model.errors.full_messages.each do |message| %>
            <li>
              <%= message %>
            </li>
          <% end %>
      </ul>
    </div>
  <% end %>
</section>

app/views/users/_sign_up_form.html.erb
<%= form_with model: @user, url: sign_up_path, local: true, data: { turbo: false }, class: "ui form" do |f| %>
  <div class="<%= class_names('required', 'field', error: @user.errors[:username].any? ) %>">
    <%= f.label :username %>
    <div class="ui left icon input">
      <%= f.text_field :username, placeholder: "Username" %>
      <i class="user icon"></i>
    </div>
  </div>
  <div class="<%= class_names('required', 'field', error: @user.errors[:password].any? ) %>">
    <%= f.label :password %>
    <div class="ui left icon input">
      <%= f.password_field :password, placeholder: "Password" %>
      <i class="lock icon"></i>
    </div>
  </div>
  <div class="<%= class_names('required', 'field', error: @user.errors[:password_confirmation].any? ) %>">
    <%= f.label :password_confirmation, "Repeat password" %>
    <div class="ui left icon input">
      <%= f.password_field :password_confirmation, placeholder: "Repeat password" %>
      <i class="lock icon"></i>
    </div>
  </div>
  <div class="<%= class_names('required', 'inline', 'field', error: @user.errors[:terms].any? ) %>">
    <div class="ui checkbox">
      <%= f.check_box :terms %>
      <%= f.label :terms, raw("I agree to the <a href=\"#\">terms and conditions.</a>") %>
    </div>
  </div>
  <%= f.submit "Sign up", class: "ui submit primary button" %>
<% end %>

app/views/users/edit.html.erb
<%= render "shared/validation_errors", model: @user %>

<div class="ui top attached center aligned header">
  <h1 class="ui header">
  Change password
  </h1>
</div>

<section class="ui fluid attached huge segment padded secondary">

  <%= form_with model: @user, url: user_path(@user), local: true, data: { turbo: false }, class: "ui form" do |f| %>

    <div class="<%= class_names('required', 'field', error: @user.errors[:old_password].any? ) %>">
      <%= f.label :old_password %>
      <div class="ui left icon input">
        <%= f.password_field :old_password, placeholder: "Old password" %>
        <i class="lock icon"></i>
      </div>
    </div>

    <div class="<%= class_names('required', 'field', error: @user.errors[:password].any? ) %>">
      <%= f.label :password, "New password" %>
      <div class="ui left icon input">
        <%= f.password_field :password, placeholder: "New password" %>
        <i class="lock icon"></i>
      </div>
    </div>

    <div class="<%= class_names('required', 'field', error: @user.errors[:password_confirmation].any? ) %>">
      <%= f.label :password_confirmation, "Repeat new password" %>
      <div class="ui left icon input">
        <%= f.password_field :password_confirmation, placeholder: "Repeat new password" %>
        <i class="lock icon"></i>
      </div>
    </div>

    <%= f.submit "Change password", class: "ui submit primary button" %>
  <% end %>

</section>

app/views/users/new.html.erb
<main class="ui grid centered">
  <div class="twelve wide column">

    <%= render "shared/validation_errors", model: @user %>

    <div class="ui top attached center aligned header">
      <h1 class="ui header">
      Create new account
      </h1>
      <h2 class="ui sub header">
      Join the community
      </h2>
    </div>

    <section class="ui fluid attached huge segment çpadded secondary">
      <%= render "sign_up_form" %>
    </section>

    <div class="ui bottom attached warning message">
      <i class="icon help"></i>
      Already signed up? <%= link_to "Login here", login_path%>
    </div>

  </div>
</main>

app/views/users/show.html.erb
<main>
  <section class="ui sizer vertial segment basic">
      <h1 class="ui massive center aligned icon header">
      <%= get_avatar_for_username @user.username %>
        <div class="content">
          <%= @user.username %> profile
        </div>
      </h1>
  </section>

  <section class="ui grid centered">

    <div class="row">
      <div class="ten wide column">
        <section class="ui segments">
          <div class="ui raised segment center aligned">
            <p class="ui text">
              Joined
              <b><i>
                <%= time_ago_in_words @user.created_at %>
              </b></i>
              ago
            </p>
          </div>
        </section>
      </div>

    </div>

    <section class="twelve wide column center aligned">
      <%= link_to "Back", root_path, class: "ui button primary big" %>
    </section>

  </section>

</main>